# Generated by Django 4.1.13 on 2024-09-17 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_pray_description_pray_email_photo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='pray',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
